/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface ComponentData {
  name: string
  importInfo: ImportInfo
  usages: Array<UsageLocation>
}

export interface ImportInfo {
  name: string
  isDefault: boolean
  line: number
}

export interface ImportSourceData {
  source: string
  components: Array<ComponentData>
}

/** Parse a single React file and extract component usage information */
export declare function parseFile(filePath: string, sourceCode: string): ParseResult

/** Parse an entire React project and generate a component atlas */
export declare function parseProject(projectRoot: string): string

export interface ParseResult {
  filePath: string
  bySource: Array<ImportSourceData>
}

export interface PropUsage {
  name: string
  value?: string
  line: number
}

export interface UsageLocation {
  line: number
  col: number
  props: Array<PropUsage>
}
